name: Firebase CI deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "beta"

      - name: Enable Flutter Web
        run: |
          flutter config --enable-web

      - name: Install dependencies
        run: flutter packages get

      - name: Build web
        run: flutter build web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.FIREBASE_TOKEN}}
          publish_dir: ./build/web
