name: Firebase CI deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "beta"

      - name: Build Flutter Web
        run: |
          npm ci && npm run build

      - name: Firebase Deploy
        run: |
          sudo npm install -g firebase-tools
          firebase deploy --token ${{secrets.FIREBASE_TOKEN}}
