name: Firebase CI deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1.4.0
        with:
          channel: "beta"

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter packages get

      - name: Build web
        run: flutter build web --release

      - name: Install firebase
        run: sudo npm install -g firebase-tools

      - name: Firebase deploy
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
